from typing import List, Optional, Literal
from pydantic import BaseModel, Field


class ResearchRequest(BaseModel):
    """
    Input received from the user.
    """

    query: str = Field(
        ...,
        description="The user's research request."
    )

    research_depth: Literal[
        "basic",
        "intermediate",
        "deep"
    ] = Field(
        default="deep",
        description="Level of research required."
    )

    output_format: Literal[
        "markdown",
        "json",
        "report"
    ] = Field(
        default="report",
        description="Desired output format."
    )

    max_sources: int = Field(
        default=10,
        ge=1,
        le=100,
        description="Maximum number of sources to collect."
    )

    include_citations: bool = Field(
        default=True,
        description="Whether citations should be included."
    )


class ResearchTask(BaseModel):
    """
    A single executable task generated by the planner.
    """

    task_id: int

    title: str

    description: str

    task_type: Literal[
        "search",
        "crawl",
        "extract",
        "summarize",
        "compare",
        "verify",
        "reason",
        "report",
        "memory"
    ]

    tool_name: Optional[str] = Field(
        default=None,
        description="Name of the MCP tool to execute."
    )

    tool_arguments: dict = Field(
        default_factory=dict,
        description="Arguments passed to the MCP tool."
    )

    priority: int = Field(
        default=1,
        ge=1,
        le=5
    )

    depends_on: List[int] = Field(
        default_factory=list
    )

    expected_output: str


class ResearchPlan(BaseModel):
    """
    Complete execution plan produced by the planner.
    """

    objective: str

    research_scope: str

    estimated_steps: int

    tasks: List[ResearchTask]

    final_output_format: Literal[
        "markdown",
        "json",
        "report"
    ] = "report"

